---
- hosts: local
  connection: local
  gather_facts: no

  tasks:
  - name: resize raspi machine
    docker_container:
      name: raspi
      image: ptrsr/pi-ci
      command: resize -y {{ host.size }}
      state: started
      detach: false
      volumes:
        - "{{ host.dist_dir|default(omit) }}:/dist"
