---
- hosts: raspi
  gather_facts: no

  tasks:
  - name: shutdown vm
    shell: shutdown now
    become: true
    async: 1
    poll: 0


- hosts: local
  connection: local
  gather_facts: no
  
  tasks:
  - name: wait for shutdown
    pause:
      seconds: 10
    
  - name: stop raspi container
    docker_container:
      name: raspi
      state: absent
