---
- hosts: raspi
  gather_facts: no

  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    ansible.builtin.file:
      path: /var/lib/dpkg/status
      state: touch
      mode: u=rw,g=r,o=r
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
  - name: install dependencies
    apt:
      pkg:
      - whois
      state: present
    register: result
    retries: 3
    until: result is not failed
