---
- hosts: raspi
  gather_facts: no

  tasks:
  - name: Workaround dpkg bug not recognizing the status file
    ansible.builtin.file:
      path: /var/lib/dpkg/status
      state: touch
      mode: u=rw,g=r,o=r
  - name: Install dependencies
    apt:
      pkg:
      - whois
      state: present
      update_cache: yes
    register: result
    retries: 3
    until: result is not failed
