---
# Initialize raspi
- import_playbook: virtual/pici.yml
  vars:
    commands:
      - init
      - resize -y {{ host.size }}
      - start

# Configure raspi
- import_playbook: setup/packages.yml

# Export raspi vm
- import_playbook: virtual/pici.yml
  vars:
    commands:
      - export

# Stop raspi vm
- import_playbook: virtual/stop.yml
