name: PI-TEMPLATE
on: [push]

env:
  PI_CI: ptrsr/pi-ci:0.7

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull $PI_CI

      - name: Build Docker image
        run: docker build -t ansible-pi-template .

      - name: Create RASPI_NETWORK
        run: docker network create raspi_network

      - name: Pull Docker image
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock --network raspi_network --name ansible-pi-template

      - name: Export image
        run: |
          docker run -i --rm \
          -v $GITHUB_WORKSPACE/dist/:/dist \
          $PI_CI export -o /dist/distro.img

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: distro
          path: dist/distro.img
